# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\final work\FinalWork-Ms.Wu\Project\Gui\车牌识别调试窗口.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 215)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.photo_widget = QtWidgets.QWidget(self.centralWidget)
        self.photo_widget.setGeometry(QtCore.QRect(20, 20, 311, 61))
        self.photo_widget.setObjectName("photo_widget")
        self.pushButton = QtWidgets.QPushButton(self.photo_widget)
        self.pushButton.setGeometry(QtCore.QRect(220, 20, 80, 23))
        self.pushButton.setObjectName("pushButton")
        self.photo = QtWidgets.QLabel(self.photo_widget)
        self.photo.setGeometry(QtCore.QRect(40, 10, 136, 36))
        self.photo.setText("")
        self.photo.setScaledContents(True)
        self.photo.setOpenExternalLinks(True)
        self.photo.setObjectName("photo")
        self.char_widget = QtWidgets.QWidget(self.centralWidget)
        self.char_widget.setGeometry(QtCore.QRect(20, 80, 311, 81))
        self.char_widget.setObjectName("char_widget")
        self.label_text1 = QtWidgets.QLabel(self.char_widget)
        self.label_text1.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_text1.setObjectName("label_text1")
        self.layoutWidget = QtWidgets.QWidget(self.char_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.char0 = QtWidgets.QLabel(self.layoutWidget)
        self.char0.setText("")
        self.char0.setScaledContents(True)
        self.char0.setObjectName("char0")
        self.horizontalLayout.addWidget(self.char0)
        self.char1 = QtWidgets.QLabel(self.layoutWidget)
        self.char1.setText("")
        self.char1.setScaledContents(True)
        self.char1.setObjectName("char1")
        self.horizontalLayout.addWidget(self.char1)
        self.char2 = QtWidgets.QLabel(self.layoutWidget)
        self.char2.setText("")
        self.char2.setScaledContents(True)
        self.char2.setObjectName("char2")
        self.horizontalLayout.addWidget(self.char2)
        self.char3 = QtWidgets.QLabel(self.layoutWidget)
        self.char3.setText("")
        self.char3.setScaledContents(True)
        self.char3.setObjectName("char3")
        self.horizontalLayout.addWidget(self.char3)
        self.char4 = QtWidgets.QLabel(self.layoutWidget)
        self.char4.setText("")
        self.char4.setScaledContents(True)
        self.char4.setObjectName("char4")
        self.horizontalLayout.addWidget(self.char4)
        self.char5 = QtWidgets.QLabel(self.layoutWidget)
        self.char5.setText("")
        self.char5.setScaledContents(True)
        self.char5.setObjectName("char5")
        self.horizontalLayout.addWidget(self.char5)
        self.char6 = QtWidgets.QLabel(self.layoutWidget)
        self.char6.setText("")
        self.char6.setScaledContents(True)
        self.char6.setObjectName("char6")
        self.horizontalLayout.addWidget(self.char6)
        self.result_widget = QtWidgets.QWidget(self.centralWidget)
        self.result_widget.setGeometry(QtCore.QRect(20, 160, 311, 31))
        self.result_widget.setObjectName("result_widget")
        self.layoutWidget1 = QtWidgets.QWidget(self.result_widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 291, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_text2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_text2.setEnabled(True)
        self.label_text2.setObjectName("label_text2")
        self.horizontalLayout_3.addWidget(self.label_text2)
        self.result = QtWidgets.QTextEdit(self.layoutWidget1)
        self.result.setObjectName("result")
        self.horizontalLayout_3.addWidget(self.result)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.getimage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "车牌识别系统"))
        self.pushButton.setText(_translate("MainWindow", "加载车牌图片"))
        self.label_text1.setText(_translate("MainWindow", "车牌字符分割："))
        self.label_text2.setText(_translate("MainWindow", "识别结果："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

